### ISSUE TITLE
Probleme de clonage template

### ISSUE THREAD

**Issue by dabofonsa** [dabofonsa/fonsa#1]
![erreurdeclonage](https://user-images.githubusercontent.com/33979559/35678890-fe9128a0-074c-11e8-8483-c9e14bc010cf.PNG)

Je n'arrive pas à cloner mon repository htmltemplate dans mon dossier Template

**Comment by moussadiallo** [comment]
Là tu as un problem de droit sur le repo, de deux choses l'une:
- soit l'utilisateur git qui a créer le repo est différent de l'utilisateur qui est enregistré dans ta machine local et qui essaye de cloner
- soit le repo n'existe pas, c'est probablement le cas, essaye de créer un autre repo pour voir

**Comment by dabofonsa** [comment]
J'ai crée un autre repo mais il me retourne la même erreur
